In [ ]:
from langchain_community.document_loaders import PyPDFLoader

loader=PyPDFLoader("/Users/sreesekhar/IAI/AgenticGenerativeAI/week9/lab/data/nke-10k-2023.pdf")
documents=loader.load()
documents

In [ ]:
from langchain_community.vectorstores import FAISS
from langchain_huggingface.embeddings import  HuggingFaceEmbeddings

embedding_llm=HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")

In [ ]:
faiss_db=FAISS.from_documents(documents,embedding_llm)

In [ ]:
faiss_db.similarity_search("what was the nike's revenue last year")

In [ ]:
retriever=faiss_db.as_retriever()

In [ ]:
import os

#os.environ["OPENAI_API_KEY"]="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"

In [ ]:
from langchain_openai import ChatOpenAI
from langchain_openai import OpenAIEmbeddings
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from dotenv import load_dotenv

In [ ]:
load_dotenv()

In [ ]:
model=ChatOpenAI(model="gpt-4o")

generator_llm=LangchainLLMWrapper(model)
generator_embeddings=LangchainEmbeddingsWrapper(OpenAIEmbeddings())

In [ ]:
from ragas.testset import TestsetGenerator

generator=TestsetGenerator(llm=generator_llm,embedding_model=generator_embeddings)

In [ ]:
test_dataset=generator.generate_with_langchain_docs(documents,testset_size=10)

In [ ]:
#test_dataset.to_pandas().to_csv("./testset.csv")

In [ ]:
from langchain_ollama.llms import OllamaLLM

inf_llm=OllamaLLM(model="chevalblanc/gpt-4o-mini")

In [ ]:
from langchain_core.prompts import ChatPromptTemplate

system_prompt="""
use the following piece of context from nike financial data to answer the user questions at the end.
if you don't know the answer, say that you don't know. Don't make up your own answers.

Context:
==============
{context}
"""
def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in documents)

prompt=ChatPromptTemplate.from_messages(
    [
        ("system",system_prompt),
        ("human","{input}")
    ]
)

In [ ]:
from langchain.chains import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain

qachain=create_stuff_documents_chain(inf_llm,prompt)

rag_chain=create_retrieval_chain(retriever,qachain)

In [ ]:
rag_chain.invoke({"input":"what is the annual profit of Nike"})

#### Create Evaluation Dataset

In [ ]:
from ragas import evaluate

In [80]:
def parse_contexts(data):
    return [doc.page_content for doc in data]

In [84]:
from datasets import Dataset

def create_evaluation_dataset(chain,test_dataset):
    
    res_set={
        
        "question":[],
        "answer":[],
        "contexts":[],
        "ground_truth":[]
    }
    
    for _, row in test_dataset.to_pandas().iterrows():
        
       result=chain.invoke({"input":row["user_input"]})
        
       res_set["question"].append(row["user_input"]) 
       res_set["answer"].append(result["answer"])
       
       contexts= parse_contexts(result["context"])
       
       if not len(contexts):
           print("no contex found for the question")
       res_set["contexts"].append(contexts)
       res_set["ground_truth"].append(str(row["reference"]))
    
    return Dataset.from_dict(res_set)

In [85]:
eval_dataset=create_evaluation_dataset(rag_chain,test_dataset)

In [86]:
eval_dataset.to_pandas().to_csv("./evalset.csv")

In [98]:
from ragas import evaluate
from ragas.run_config import RunConfig

def evaluate_results(evaldataset,metrics,llm,emb_model):
    
    run_config=RunConfig(max_retries=5)
    eval_results=evaluate(
        evaldataset,
        metrics=metrics,
        run_config=run_config,
        llm=llm,
        embeddings=emb_model
        
    )
    
    results=eval_results.to_pandas()
    
    return results

In [89]:
from ragas.metrics import context_recall,context_precision

context_recall_metrics=evaluate_results(eval_dataset,[context_recall],generator_llm,generato_embeddings)

Evaluating: 100%|██████████| 10/10 [00:49<00:00,  4.99s/it]

In [90]:
context_recall_metrics.describe()

       context_recall
count       10.000000
mean         0.775000
std          0.351474
min          0.000000
25%          0.687500
50%          1.000000
75%          1.000000
max          1.000000

In [91]:
from ragas.metrics import context_recall,context_precision

context_precission_metrics=evaluate_results(eval_dataset,[context_precision],generator_llm,generato_embeddings)

Evaluating: 100%|██████████| 10/10 [01:46<00:00, 10.66s/it]

In [92]:
context_precission_metrics.describe()

       context_precision
count          10.000000
mean            0.663889
std             0.421972
min             0.000000
25%             0.375000
50%             0.902778
75%             1.000000
max             1.000000

In [93]:
from ragas.metrics import faithfulness,answer_relevancy

faithfulness_metrics=evaluate_results(eval_dataset,[faithfulness],generator_llm,generato_embeddings)

Evaluating: 100%|██████████| 10/10 [01:32<00:00,  9.27s/it]

In [95]:
faithfulness_metrics.describe()

       faithfulness
count     10.000000
mean       0.339030
std        0.222544
min        0.000000
25%        0.233333
50%        0.350446
75%        0.497059
max        0.666667

In [99]:
answer_relevancy_metrics=evaluate_results(eval_dataset,[answer_relevancy],generator_llm,generato_embeddings)

Evaluating:   0%|          | 0/10 [00:00<?, ?it/s]Exception raised in Job[9]: AuthenticationError(Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-proj-********************************************************************************************************************************************************yqUA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}})
Evaluating:  10%|█         | 1/10 [00:01<00:09,  1.06s/it]Exception raised in Job[8]: AuthenticationError(Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-proj-********************************************************************************************************************************************************yqUA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}})
Evaluating:  20%|██        | 2/10 [00:01<00:04,  1.67it/s]Exception raised in Job[7]: AuthenticationError(Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-proj-********************************************************************************************************************************************************yqUA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}})
Evaluating:  30%|███       | 3/10 [00:01<00:03,  1.99it/s]Exception raised in Job[4]: AuthenticationError(Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-proj-********************************************************************************************************************************************************yqUA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}})
Exception raised in Job[0]: AuthenticationError(Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-proj-********************************************************************************************************************************************************yqUA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}})
Exception raised in Job[3]: AuthenticationError(Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-proj-********************************************************************************************************************************************************yqUA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}})
Exception raised in Job[6]: AuthenticationError(Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-proj-********************************************************************************************************************************************************yqUA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}})
Exception raised in Job[2]: AuthenticationError(Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-proj-********************************************************************************************************************************************************yqUA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}})
Evaluating:  40%|████      | 4/10 [00:02<00:03,  1.82it/s]Exception raised in Job[5]: AuthenticationError(Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-proj-********************************************************************************************************************************************************yqUA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}})
Exception raised in Job[1]: AuthenticationError(Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-proj-********************************************************************************************************************************************************yqUA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}})
Evaluating: 100%|██████████| 10/10 [00:02<00:00,  3.93it/s]

In [97]:
answer_relevancy_metrics.describe()

       answer_relevancy
count               0.0
mean                NaN
std                 NaN
min                 NaN
25%                 NaN
50%                 NaN
75%                 NaN
max                 NaN